"""Normalization data for US address parsing."""

from typing import Dict, FrozenSet

ADDRESS_KINDS: FrozenSet[str] = frozenset({"street", "route", "po_box", "unknown"})

STATE_ABBREVIATIONS: FrozenSet[str] = frozenset(
    {
        "AL",
        "AK",
        "AZ",
        "AR",
        "CA",
        "CO",
        "CT",
        "DE",
        "FL",
        "GA",
        "HI",
        "ID",
        "IL",
        "IN",
        "IA",
        "KS",
        "KY",
        "LA",
        "ME",
        "MD",
        "MA",
        "MI",
        "MN",
        "MS",
        "MO",
        "MT",
        "NE",
        "NV",
        "NH",
        "NJ",
        "NM",
        "NY",
        "NC",
        "ND",
        "OH",
        "OK",
        "OR",
        "PA",
        "RI",
        "SC",
        "SD",
        "TN",
        "TX",
        "UT",
        "VT",
        "VA",
        "WA",
        "WV",
        "WI",
        "WY",
        "DC",
        "AA",
        "AE",
        "AP",
    }
)

NON_US_COUNTRY_TERMS: FrozenSet[str] = frozenset(
    {
        "AUSTRALIA",
        "BRASIL",
        "BRAZIL",
        "CANADA",
        "DEUTSCHLAND",
        "FRANCE",
        "GERMANY",
        "INDIA",
        "IRELAND",
        "ITALY",
        "JAPAN",
        "MEXICO",
        "NETHERLANDS",
        "NEW ZEALAND",
        "SPAIN",
        "UNITED KINGDOM",
        "UK",
    }
)

CANADIAN_PROVINCES: FrozenSet[str] = frozenset(
    {
        "AB",
        "BC",
        "MB",
        "NB",
        "NL",
        "NS",
        "NT",
        "NU",
        "ON",
        "PE",
        "QC",
        "SK",
        "YT",
    }
)

DIRECTIONALS: Dict[str, str] = {
    "N": "N",
    "NORTH": "N",
    "S": "S",
    "SOUTH": "S",
    "E": "E",
    "EAST": "E",
    "W": "W",
    "WEST": "W",
    "NE": "NE",
    "NORTHEAST": "NE",
    "NW": "NW",
    "NORTHWEST": "NW",
    "SE": "SE",
    "SOUTHEAST": "SE",
    "SW": "SW",
    "SOUTHWEST": "SW",
}

UNIT_TYPES: Dict[str, str] = {
    "APT": "APT",
    "APARTMENT": "APT",
    "BSMT": "BSMT",
    "BASEMENT": "BSMT",
    "BLDG": "BLDG",
    "BUILDING": "BLDG",
    "DEPT": "DEPT",
    "DEPARTMENT": "DEPT",
    "FL": "FL",
    "FLOOR": "FL",
    "FRNT": "FRNT",
    "FRONT": "FRNT",
    "HNGR": "HNGR",
    "HANGAR": "HNGR",
    "KEY": "KEY",
    "LBBY": "LBBY",
    "LOBBY": "LBBY",
    "LOT": "LOT",
    "LOWR": "LOWR",
    "LOWER": "LOWR",
    "NO": "UNIT",
    "NUMBER": "UNIT",
    "OFC": "OFC",
    "OFFICE": "OFC",
    "PH": "PH",
    "PENTHOUSE": "PH",
    "PIER": "PIER",
    "REAR": "REAR",
    "RM": "RM",
    "ROOM": "RM",
    "SIDE": "SIDE",
    "SLIP": "SLIP",
    "SPC": "SPC",
    "SPACE": "SPC",
    "STOP": "STOP",
    "STE": "STE",
    "SUITE": "STE",
    "TRLR": "TRLR",
    "TRAILER": "TRLR",
    "UNIT": "UNIT",
    "UPPR": "UPPR",
    "UPPER": "UPPR",
}

STREET_SUFFIXES: Dict[str, str] = {
    "ALLEE": "ALY",
    "ALLEY": "ALY",
    "ALY": "ALY",
    "AV": "AVE",
    "AVE": "AVE",
    "AVEN": "AVE",
    "AVENU": "AVE",
    "AVENUE": "AVE",
    "BAYOO": "BYU",
    "BAYOU": "BYU",
    "BCH": "BCH",
    "BEACH": "BCH",
    "BEND": "BND",
    "BND": "BND",
    "BLVD": "BLVD",
    "BOULEVARD": "BLVD",
    "BOT": "BTM",
    "BOTTM": "BTM",
    "BOTTOM": "BTM",
    "BR": "BR",
    "BRANCH": "BR",
    "BRG": "BRG",
    "BRIDGE": "BRG",
    "BROOK": "BRK",
    "BROOKS": "BRKS",
    "BRK": "BRK",
    "BRKS": "BRKS",
    "BURG": "BG",
    "BURGS": "BGS",
    "BYPA": "BYP",
    "BYPAS": "BYP",
    "BYP": "BYP",
    "BYPASS": "BYP",
    "BYU": "BYU",
    "CAMP": "CP",
    "CANYN": "CYN",
    "CANYON": "CYN",
    "CAPE": "CPE",
    "CAUSEWAY": "CSWY",
    "CAUSWAY": "CSWY",
    "CEN": "CTR",
    "CENT": "CTR",
    "CENTER": "CTR",
    "CENTERS": "CTRS",
    "CENTR": "CTR",
    "CENTRE": "CTR",
    "CIRC": "CIR",
    "CIRCL": "CIR",
    "CIR": "CIR",
    "CIRCLE": "CIR",
    "CIRCLES": "CIRS",
    "CIRS": "CIRS",
    "CLIFF": "CLF",
    "CLIFFS": "CLFS",
    "CLF": "CLF",
    "CLFS": "CLFS",
    "CLB": "CLB",
    "CLUB": "CLB",
    "CMP": "CP",
    "COMMON": "CMN",
    "COMMONS": "CMNS",
    "CORNER": "COR",
    "CORNERS": "CORS",
    "COR": "COR",
    "CORS": "CORS",
    "COURSE": "CRSE",
    "CRSE": "CRSE",
    "CP": "CP",
    "CPE": "CPE",
    "CRES": "CRES",
    "CRESCENT": "CRES",
    "CREST": "CRST",
    "CROSSING": "XING",
    "CROSSROAD": "XRD",
    "CROSSROADS": "XRDS",
    "CRST": "CRST",
    "CSWY": "CSWY",
    "CTR": "CTR",
    "CTRS": "CTRS",
    "CT": "CT",
    "COURT": "CT",
    "COURTS": "CTS",
    "CTS": "CTS",
    "CURVE": "CURV",
    "CURV": "CURV",
    "CV": "CV",
    "COVE": "CV",
    "COVES": "CVS",
    "CVS": "CVS",
    "CYN": "CYN",
    "DALE": "DL",
    "DAM": "DM",
    "DIV": "DV",
    "DIVIDE": "DV",
    "DL": "DL",
    "DM": "DM",
    "DR": "DR",
    "DRIV": "DR",
    "DRIVE": "DR",
    "DRIVES": "DRS",
    "DRS": "DRS",
    "DVD": "DV",
    "DV": "DV",
    "EST": "EST",
    "ESTATE": "EST",
    "ESTATES": "ESTS",
    "ESTS": "ESTS",
    "EXP": "EXPY",
    "EXPR": "EXPY",
    "EXPRESS": "EXPY",
    "EXPY": "EXPY",
    "EXPRESSWAY": "EXPY",
    "EXT": "EXT",
    "EXTENSION": "EXT",
    "EXTENSIONS": "EXTS",
    "EXTN": "EXT",
    "EXTNSN": "EXT",
    "EXTS": "EXTS",
    "FALL": "FALL",
    "FALLS": "FLS",
    "FERRY": "FRY",
    "FIELD": "FLD",
    "FIELDS": "FLDS",
    "FLAT": "FLT",
    "FLATS": "FLTS",
    "FLD": "FLD",
    "FLDS": "FLDS",
    "FLS": "FLS",
    "FLT": "FLT",
    "FLTS": "FLTS",
    "FORD": "FRD",
    "FORDS": "FRDS",
    "FOREST": "FRST",
    "FORESTS": "FRST",
    "FORG": "FRG",
    "FORGE": "FRG",
    "FORGES": "FRGS",
    "FORK": "FRK",
    "FORKS": "FRKS",
    "FORT": "FT",
    "FRD": "FRD",
    "FRDS": "FRDS",
    "FRG": "FRG",
    "FRGS": "FRGS",
    "FRK": "FRK",
    "FRKS": "FRKS",
    "FRRY": "FRY",
    "FRST": "FRST",
    "FT": "FT",
    "FRY": "FRY",
    "FREEWAY": "FWY",
    "FWY": "FWY",
    "GARDEN": "GDN",
    "GARDENS": "GDNS",
    "GARDN": "GDN",
    "GATEWAY": "GTWY",
    "GATEWY": "GTWY",
    "GATWAY": "GTWY",
    "GDN": "GDN",
    "GDNS": "GDNS",
    "GTWAY": "GTWY",
    "GTWY": "GTWY",
    "GLEN": "GLN",
    "GLENS": "GLNS",
    "GLN": "GLN",
    "GLNS": "GLNS",
    "GREEN": "GRN",
    "GREENS": "GRNS",
    "GRN": "GRN",
    "GRNS": "GRNS",
    "GRV": "GRV",
    "GROVE": "GRV",
    "GROVES": "GRVS",
    "GRVS": "GRVS",
    "HARB": "HBR",
    "HARBOR": "HBR",
    "HARBORS": "HBRS",
    "HARBR": "HBR",
    "HAVEN": "HVN",
    "HBR": "HBR",
    "HBRS": "HBRS",
    "HEIGHT": "HTS",
    "HEIGHTS": "HTS",
    "HGTS": "HTS",
    "HILL": "HL",
    "HILLS": "HLS",
    "HL": "HL",
    "HLLW": "HOLW",
    "HLS": "HLS",
    "HOLLOW": "HOLW",
    "HOLLOWS": "HOLW",
    "HOLW": "HOLW",
    "HOLWS": "HOLW",
    "HIGHWAY": "HWY",
    "HIGHWY": "HWY",
    "HIWAY": "HWY",
    "HIWY": "HWY",
    "HT": "HTS",
    "HTS": "HTS",
    "HVN": "HVN",
    "HWAY": "HWY",
    "HWY": "HWY",
    "INLET": "INLT",
    "INLT": "INLT",
    "IS": "IS",
    "ISLAND": "IS",
    "ISLANDS": "ISS",
    "ISLE": "ISLE",
    "ISLES": "ISLE",
    "ISS": "ISS",
    "JCT": "JCT",
    "JCTION": "JCT",
    "JCTN": "JCT",
    "JCTNS": "JCTS",
    "JUNCTION": "JCT",
    "JUNCTIONS": "JCTS",
    "JCTS": "JCTS",
    "KEYS": "KYS",
    "KNOL": "KNL",
    "KNOLL": "KNL",
    "KNOLLS": "KNLS",
    "KNL": "KNL",
    "KNLS": "KNLS",
    "KY": "KY",
    "KYS": "KYS",
    "LA": "LN",
    "LANE": "LN",
    "LIGHT": "LGT",
    "LIGHTS": "LGTS",
    "LGT": "LGT",
    "LGTS": "LGTS",
    "LOAF": "LF",
    "LF": "LF",
    "LN": "LN",
    "LOCK": "LCK",
    "LOCKS": "LCKS",
    "LCK": "LCK",
    "LCKS": "LCKS",
    "LDG": "LDG",
    "LDGE": "LDG",
    "LODGE": "LDG",
    "LOOP": "LOOP",
    "LOOPS": "LOOP",
    "MALL": "MALL",
    "MANOR": "MNR",
    "MANORS": "MNRS",
    "MEADOW": "MDW",
    "MEADOWS": "MDWS",
    "MEDOWS": "MDWS",
    "MEWS": "MEWS",
    "MILL": "ML",
    "MILLS": "MLS",
    "MISSION": "MSN",
    "MISSN": "MSN",
    "ML": "ML",
    "MLS": "MLS",
    "MNR": "MNR",
    "MNRS": "MNRS",
    "MNT": "MT",
    "MNTN": "MTN",
    "MNTNS": "MTNS",
    "MOTORWAY": "MTWY",
    "MOUNT": "MT",
    "MOUNTAIN": "MTN",
    "MOUNTAINS": "MTNS",
    "MSN": "MSN",
    "MSSN": "MSN",
    "MT": "MT",
    "MTIN": "MTN",
    "MTN": "MTN",
    "MTNS": "MTNS",
    "MTWY": "MTWY",
    "NECK": "NCK",
    "NCK": "NCK",
    "ORCH": "ORCH",
    "ORCHARD": "ORCH",
    "ORCHRD": "ORCH",
    "OVERPASS": "OPAS",
    "OPAS": "OPAS",
    "PARK": "PARK",
    "PARKS": "PARK",
    "PARKWAY": "PKWY",
    "PARKWAYS": "PKWY",
    "PASS": "PASS",
    "PASSAGE": "PSGE",
    "PATH": "PATH",
    "PATHS": "PATH",
    "PIKE": "PIKE",
    "PIKES": "PIKE",
    "PINE": "PNE",
    "PINES": "PNES",
    "PKWY": "PKWY",
    "PKWYS": "PKWY",
    "PLACE": "PL",
    "PL": "PL",
    "PLAZA": "PLZ",
    "PLZA": "PLZ",
    "PLZ": "PLZ",
    "PNE": "PNE",
    "PNES": "PNES",
    "POINT": "PT",
    "POINTS": "PTS",
    "PORT": "PRT",
    "PORTS": "PRTS",
    "PRAIRIE": "PR",
    "PR": "PR",
    "PRARIE": "PR",
    "PRK": "PARK",
    "PRR": "PR",
    "PRT": "PRT",
    "PRTS": "PRTS",
    "PT": "PT",
    "PTS": "PTS",
    "RAD": "RADL",
    "RADIEL": "RADL",
    "RADIAL": "RADL",
    "RADL": "RADL",
    "RAMP": "RAMP",
    "RANCH": "RNCH",
    "RANCHES": "RNCH",
    "RAPID": "RPD",
    "RAPIDS": "RPDS",
    "RD": "RD",
    "ROAD": "RD",
    "ROADS": "RDS",
    "RDS": "RDS",
    "REST": "RST",
    "RIDGE": "RDG",
    "RIDGES": "RDGS",
    "RDG": "RDG",
    "RDGS": "RDGS",
    "RIVER": "RIV",
    "RIV": "RIV",
    "RIVR": "RIV",
    "RNCH": "RNCH",
    "RNCHS": "RNCH",
    "ROW": "ROW",
    "RPD": "RPD",
    "RPDS": "RPDS",
    "RST": "RST",
    "RVR": "RIV",
    "RUN": "RUN",
    "RUE": "RUE",
    "SHL": "SHL",
    "SHLS": "SHLS",
    "SHOAL": "SHL",
    "SHOALS": "SHLS",
    "SHOAR": "SHR",
    "SHOARS": "SHRS",
    "SHORE": "SHR",
    "SHORES": "SHRS",
    "SHR": "SHR",
    "SHRS": "SHRS",
    "SKYWAY": "SKWY",
    "SKWY": "SKWY",
    "SMT": "SMT",
    "SPG": "SPG",
    "SPGS": "SPGS",
    "SPRING": "SPG",
    "SPRINGS": "SPGS",
    "SPRNG": "SPG",
    "SPRNGS": "SPGS",
    "SPUR": "SPUR",
    "SPURS": "SPUR",
    "SQ": "SQ",
    "SQR": "SQ",
    "SQRE": "SQ",
    "SQRS": "SQS",
    "SQUARE": "SQ",
    "SQUARES": "SQS",
    "SQS": "SQS",
    "STA": "STA",
    "STATION": "STA",
    "STATN": "STA",
    "ST": "ST",
    "STRA": "STRA",
    "STRAV": "STRA",
    "STRAVEN": "STRA",
    "STRAVENUE": "STRA",
    "STRAVN": "STRA",
    "STREAM": "STRM",
    "STREET": "ST",
    "STREETS": "STS",
    "STREME": "STRM",
    "STRM": "STRM",
    "STS": "STS",
    "SUMIT": "SMT",
    "SUMITT": "SMT",
    "SUMMIT": "SMT",
    "TER": "TER",
    "TERRACE": "TER",
    "THROUGHWAY": "TRWY",
    "TRACE": "TRCE",
    "TRACES": "TRCE",
    "TRACE": "TRCE",
    "TRAIL": "TRL",
    "TRAILER": "TRLR",
    "TRAILS": "TRL",
    "TRCE": "TRCE",
    "TRL": "TRL",
    "TRLR": "TRLR",
    "TRWY": "TRWY",
    "TUNEL": "TUNL",
    "TUNL": "TUNL",
    "TUNLS": "TUNL",
    "TUNNEL": "TUNL",
    "TUNNELS": "TUNL",
    "TUNNL": "TUNL",
    "TURNPIKE": "TPKE",
    "TPKE": "TPKE",
    "TRNPK": "TPKE",
    "UNDERPASS": "UPAS",
    "UNION": "UN",
    "UNIONS": "UNS",
    "UN": "UN",
    "UNS": "UNS",
    "UPAS": "UPAS",
    "VALLEY": "VLY",
    "VALLEYS": "VLYS",
    "VALLY": "VLY",
    "VDCT": "VIA",
    "VIA": "VIA",
    "VIADCT": "VIA",
    "VIADUCT": "VIA",
    "VIEW": "VW",
    "VIEWS": "VWS",
    "VILL": "VLG",
    "VILLAG": "VLG",
    "VILLAGE": "VLG",
    "VILLAGES": "VLGS",
    "VILLE": "VL",
    "VL": "VL",
    "VLG": "VLG",
    "VLGS": "VLGS",
    "VLLY": "VLY",
    "VLY": "VLY",
    "VLYS": "VLYS",
    "VST": "VIS",
    "VSTA": "VIS",
    "VW": "VW",
    "VWS": "VWS",
    "VISTA": "VIS",
    "VIS": "VIS",
    "WALKS": "WALK",
    "WALK": "WALK",
    "WALL": "WALL",
    "WAY": "WAY",
    "WAYS": "WAYS",
    "WELL": "WL",
    "WELLS": "WLS",
    "WL": "WL",
    "WLS": "WLS",
    "XING": "XING",
    "XRD": "XRD",
    "XRDS": "XRDS",
}
